FROM python:3.10
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "github_archives.py" , "--f='/Users/universe/Downloads/react.json'", "--threads=80", "--extract=false", "--max-zip-size=2048"]